### ISSUE TITLE
TimeScale Formatter Error

### ISSUE THREAD

**Issue by pome90** [entronad/graphic#22] opened 2021-11-16 14:59 UTC
Hello using TimeScale class with formatter result in this error:

Dart Unhandled Exception: type '(DateTime) => String' is not a subtype of type '(dynamic) => String', stack trace: #0      TickInfoOp.evaluate.<anonymous closure>
package:graphic/…/axis/axis.dart:211

Example code:

final data = [
  {"Date": DateTime(2021, 4, 1), "ET": 6,},
  {"Date": DateTime(2021, 5, 3), "ET": 5},
  {"Date": DateTime(2021, 5, 5), "ET": 8},
  {"Date": DateTime(2021, 5, 7), "ET": 10},
  {"Date": DateTime(2021, 5, 20), "ET": 11},
  {"Date": DateTime(2021, 5, 29), "ET": 9}
];

Chart(
      data: data,
      variables: {
        'Date': Variable(
          accessor: (Map map) =>
            (map['Date'] ?? double.nan) as DateTime,
          scale: TimeScale(
            tickCount: 3,
            formatter: (x) {
              return '${x.day}';
            }
          )               
        ),
        'ET': Variable(
          accessor: (Map map) =>
            (map['ET'] ?? double.nan) as num,
        ),
      },
)

**Comment by entronad** [comment] 2021-11-18 14:02
It is caused by a generic bug of Scale.formatter.
It has been fixed in v0.5.0. Please upgrade and try.

**Closed** 2021-12-13 15:22 UTC
